; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
; for display
    adafruit/Adafruit GFX Library@^1.12.5
    adafruit/Adafruit ILI9341@^1.6.3
    ;;;;;
    ;for mpu 6050 test
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO

build_flags = 
    -I include  ; You must add this to include the header files in the include directory
monitor_speed = 115200  ; Set the baud rate for the serial monitor
